version: "3"
services:
  app:
    container_name: tarpit
    restart: always
    build: .
    ports:
      - "3000:3000"
    networks:
     - my_network
    depends_on:
      - "mysql" 

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    networks:
     - my_network
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
    ports:
      - "3306:3306"
volumes:
  dbdata:
networks:
  my_network:
    driver: bridge